[build-system]

requires = [
    "setuptools==75.8.0",
    "setuptools-scm==8.2.0"
]

build-backend = "setuptools.build_meta"

[project]
name = "PT3_tesla"
version = "0.1.0"
authors = [{name = "autor1", email = "correo@correo.com"}]
description = "TSLA Financial Direction Prediction Using Neural Networks"
requires-python = ">3.9"
dependencies = [

    "matplotlib==3.10.0",
    "numpy==2.0.2",
    "pandas==2.2.2",
    "yfinance==0.2.66",

    "dvc[gdrive]==3.67.1",

    "scikit-learn==1.6.1",
    "mlflow==3.6.0",
    "tensorflow-cpu==2.20.0",
    "joblib>=1.4.0",

    "requests==2.32.3",
    "fastapi==0.115.12",
    "uvicorn==0.34.0",
    "python-multipart==0.0.20",
    "pydantic==2.10.6"
]

[tool.setuptools.packages.find]

where = ["projects"]

include = [
    "P3_tsla*",
    "P2",
    "P1",
]