version: '3.9'

services:
  training:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: tesla_training
    volumes:
      - ../data:/app/data
    command: python src/training.py

  api:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: tesla_api
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000